export const ClientCommonErrorCodes = {
  NO_INTERNET_CONNECTION: 'NO_INTERNET_CONNECTION',
  NETWORK: 'NETWORK',
  CONTRACT_VIOLATION: 'CONTRACT_VIOLATION',
  LIFECYCLE_ERROR: 'LIFECYCLE_ERROR'
} as const
